In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('quiz_data.csv')

In [6]:
df.head()

,id,description,difficulty_level,topic,is_published,created_at,updated_at,detailed_solution,type,is_mandatory,...,created_by,updated_by,quiz_level,question_from,language,photo_url,photo_solution_url,is_saved,tag,options
0,1827,The tissue which has free surface that faces e...,NaN,structural organisation in animals,True,2024-07-02T12:43:34.360+05:30,2024-11-30T18:39:20.587+05:30,**Explanation:**\n\nThe tissue that has a free...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7321, 'description': 'Muscular tissue'..."
1,1828,Epithelial tissue is distinguished from connec...,NaN,structural organisation in animals,True,2024-07-02T12:50:56.100+05:30,2024-11-30T18:39:20.788+05:30,**Epithelial Tissue**\n\n* Epithelial tissue i...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7325, 'description': 'large extracellu..."
2,1829,The ciliated columnar epithelial cells in huma...,NaN,structural organisation in animals,True,2024-07-02T12:54:25.824+05:30,2024-11-30T18:39:20.990+05:30,**Explanation:**\n\nCiliated columnar epitheli...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7329, 'description': 'Eustachian tube ..."
3,1830,The squamous epithelium is found in,NaN,structural organisation in animals,True,2024-07-02T12:56:48.204+05:30,2024-11-30T18:39:21.192+05:30,**Explanation:**\n\nSquamous epithelium is a t...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7333, 'description': 'stomach', 'quest..."
4,1831,The kind of epithelium which forms the inner w...,NaN,structural organisation in animals,True,2024-07-02T12:58:51.241+05:30,2024-11-30T18:39:21.398+05:30,**Answer is correct because:**\n\nSquamous epi...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7337, 'description': 'cuboidal epithel..."

In [7]:
df.shape

(128, 26)

In [8]:
df.tail()

,id,description,difficulty_level,topic,is_published,created_at,updated_at,detailed_solution,type,is_mandatory,...,created_by,updated_by,quiz_level,question_from,language,photo_url,photo_solution_url,is_saved,tag,options
123,1960,"Bone is a solid, rigid connective tissue. If t...",NaN,structural organisation in animals,True,2024-07-02T17:11:47.370+05:30,2024-11-30T18:39:45.927+05:30,Bone is a solid and rigid connective tissue th...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7854, 'description': 'Become decalcifi..."
124,1961,Neurons which connect the central nervous syst...,NaN,structural organisation in animals,True,2024-07-02T17:11:47.389+05:30,2024-11-30T18:39:46.127+05:30,**Explanation:**\n\nSensory neurons are specia...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7858, 'description': 'Sensory neurons'..."
125,1962,Which type of neuron dominates in the CNS ?,NaN,structural organisation in animals,True,2024-07-02T17:11:47.411+05:30,2024-11-30T18:39:46.333+05:30,**Explanation:**\n\nThe central nervous system...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7862, 'description': 'Sensory', 'quest..."
126,1963,Mark the connective tissue which is without fi...,NaN,structural organisation in animals,True,2024-07-02T17:11:47.432+05:30,2024-11-30T18:39:46.537+05:30,**Explanation:**\n\nConnective tissues are a g...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7866, 'description': 'Areolar tissue',..."
127,1964,The percentage of inorganic and organic parts ...,NaN,structural organisation in animals,True,2024-07-02T17:11:47.452+05:30,2024-11-30T18:39:46.736+05:30,**Explanation:**\n\nThe matrix of a bone is co...,NaN,False,...,NaN,NaN,NaN,Q-bank,NaN,NaN,NaN,False,NaN,"[{'id': 7870, 'description': '40% inorganic, 6..."

In [9]:
df['options']

0      [{'id': 7321, 'description': 'Muscular tissue'...
1      [{'id': 7325, 'description': 'large extracellu...
2      [{'id': 7329, 'description': 'Eustachian tube ...
3      [{'id': 7333, 'description': 'stomach', 'quest...
4      [{'id': 7337, 'description': 'cuboidal epithel...
                             ...
123    [{'id': 7854, 'description': 'Become decalcifi...
124    [{'id': 7858, 'description': 'Sensory neurons'...
125    [{'id': 7862, 'description': 'Sensory', 'quest...
126    [{'id': 7866, 'description': 'Areolar tissue',...
127    [{'id': 7870, 'description': '40% inorganic, 6...
Name: options, Length: 128, dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   128 non-null    int64
 1   description          128 non-null    object
 2   difficulty_level     0 non-null      float64
 3   topic                128 non-null    object
 4   is_published         128 non-null    bool
 5   created_at           128 non-null    object
 6   updated_at           128 non-null    object
 7   detailed_solution    119 non-null    object
 8   type                 0 non-null      float64
 9   is_mandatory         128 non-null    bool
 10  show_in_feed         128 non-null    bool
 11  pyq_label            0 non-null      float64
 12  topic_id             128 non-null    int64
 13  reading_material_id  128 non-null    int64
 14  fixed_at             5 non-null      object
 15  fix_summary          5 non-null      object
 16  created_by           0 non-null      float64
 17  updated_by           5 non-null      object
 18  quiz_level           0 non-null      float64
 19  question_from        128 non-null    object
 20  language             0 non-null      float64
 21  photo_url            3 non-null      object
 22  photo_solution_url   0 non-null      float64
 23  is_saved             128 non-null    bool
 24  tag                  0 non-null      float64
 25  options              128 non-null    object
dtypes: bool(4), float64(8), int64(3), object(11)
memory usage: 22.6+ KB

In [11]:
df.isna().sum()

id                       0
description              0
difficulty_level       128
topic                    0
is_published             0
created_at               0
updated_at               0
detailed_solution        9
type                   128
is_mandatory             0
show_in_feed             0
pyq_label              128
topic_id                 0
reading_material_id      0
fixed_at               123
fix_summary            123
created_by             128
updated_by             123
quiz_level             128
question_from            0
language               128
photo_url              125
photo_solution_url     128
is_saved                 0
tag                    128
options                  0
dtype: int64

In [12]:
df.columns

Index(['id', 'description', 'difficulty_level', 'topic', 'is_published',
       'created_at', 'updated_at', 'detailed_solution', 'type', 'is_mandatory',
       'show_in_feed', 'pyq_label', 'topic_id', 'reading_material_id',
       'fixed_at', 'fix_summary', 'created_by', 'updated_by', 'quiz_level',
       'question_from', 'language', 'photo_url', 'photo_solution_url',
       'is_saved', 'tag', 'options'],
      dtype='object')

In [ ]:
import pandas as pd
 
# load json file using pandas
df2 = pd.read_json('quiz_data.json')
 

 

 
 
# convert dataframe to csv file
df2.to_csv("qendpoint.csv",index=False)

        id  quiz_id                       user_id  \
0   336497       51  YcDFSO4ZukTJnnFMgRNVwZTE4j42
1   336448        6  YcDFSO4ZukTJnnFMgRNVwZTE4j42
2   333330       51  YcDFSO4ZukTJnnFMgRNVwZTE4j42
3   333242        6  YcDFSO4ZukTJnnFMgRNVwZTE4j42
4   329504       51  YcDFSO4ZukTJnnFMgRNVwZTE4j42
5   328488       57  YcDFSO4ZukTJnnFMgRNVwZTE4j42
6   328414        6  YcDFSO4ZukTJnnFMgRNVwZTE4j42
7   321514       20  YcDFSO4ZukTJnnFMgRNVwZTE4j42
8   320963       24  YcDFSO4ZukTJnnFMgRNVwZTE4j42
9   320916       18  YcDFSO4ZukTJnnFMgRNVwZTE4j42
10  315179       25  YcDFSO4ZukTJnnFMgRNVwZTE4j42
11  315081       18  YcDFSO4ZukTJnnFMgRNVwZTE4j42
12  257774       58  YcDFSO4ZukTJnnFMgRNVwZTE4j42
13  195808       50  YcDFSO4ZukTJnnFMgRNVwZTE4j42

                        submitted_at                        created_at  \
0   2025-01-17 15:30:18.027000+05:30  2025-01-17 15:30:18.044000+05:30
1   2025-01-17 15:17:44.042000+05:30  2025-01-17 15:17:44.056000+05:30
2   2025-01-16 20:13:19.682000+05:30  2025-01-16 20:13:19.699000+05:30
3   2025-01-16 20:00:11.562000+05:30  2025-01-16 20:00:11.573000+05:30
4   2025-01-15 20:34:39.462000+05:30  2025-01-15 20:34:39.478000+05:30
5   2025-01-15 15:57:12.791000+05:30  2025-01-15 15:57:12.800000+05:30
6   2025-01-15 15:36:46.410000+05:30  2025-01-15 15:36:46.420000+05:30
7   2025-01-13 16:10:03.743000+05:30  2025-01-13 16:10:03.753000+05:30
8   2025-01-13 13:28:12.784000+05:30  2025-01-13 13:28:12.795000+05:30
9   2025-01-13 13:12:40.687000+05:30  2025-01-13 13:12:40.695000+05:30
10  2025-01-11 21:20:08.641000+05:30  2025-01-11 21:20:08.652000+05:30
11  2025-01-11 21:03:43.251000+05:30  2025-01-11 21:03:43.262000+05:30
12  2024-12-28 22:58:52.969000+05:30  2024-12-28 22:58:53.122000+05:30
13  2024-12-11 20:36:44.822000+05:30  2024-12-11 20:36:44.863000+05:30

                          updated_at  score  trophy_level accuracy  speed  \
0   2025-01-17 15:30:18.044000+05:30    108             2     90 %    100
1   2025-01-17 15:17:44.056000+05:30     92             1    100 %    100
2   2025-01-16 20:13:19.699000+05:30    116             2     96 %    100
3   2025-01-16 20:00:11.573000+05:30     36             2     90 %    100
4   2025-01-15 20:34:39.478000+05:30     36             3     31 %     96
5   2025-01-15 15:57:12.800000+05:30     40             3     38 %     86
6   2025-01-15 15:36:46.420000+05:30     36             3     50 %     78
7   2025-01-13 16:10:03.753000+05:30     12             2     30 %    100
8   2025-01-13 13:28:12.795000+05:30     76             2    100 %     95
9   2025-01-13 13:12:40.695000+05:30     40             1    100 %    100
10  2025-01-11 21:20:08.652000+05:30    112             2     93 %    100
11  2025-01-11 21:03:43.262000+05:30     64             3     84 %     86
12  2024-12-28 22:58:53.122000+05:30     52             2     43 %    100
13  2024-12-11 20:36:44.863000+05:30     24             3     66 %     90

    ...                 started_at                   ended_at  duration  \
0   ...  2025-01-17 15:18:30+05:30  2025-01-17 15:30:15+05:30     15:00
1   ...  2025-01-17 15:07:45+05:30  2025-01-17 15:17:41+05:30     15:00
2   ...  2025-01-16 20:01:10+05:30  2025-01-16 20:13:18+05:30     15:00
3   ...  2025-01-16 19:52:57+05:30  2025-01-16 20:00:09+05:30     15:00
4   ...  2025-01-15 20:21:25+05:30  2025-01-15 20:34:38+05:30     15:00
5   ...  2025-01-15 15:47:05+05:30  2025-01-15 15:57:11+05:30     15:00
6   ...  2025-01-15 15:23:42+05:30  2025-01-15 15:36:45+05:30     15:00
7   ...  2025-01-13 16:05:27+05:30  2025-01-13 16:10:02+05:30     15:00
8   ...  2025-01-13 13:14:17+05:30  2025-01-13 13:28:11+05:30     15:00
9   ...  2025-01-13 13:11:13+05:30  2025-01-13 13:12:39+05:30     15:00
10  ...  2025-01-11 21:04:22+05:30  2025-01-11 21:20:07+05:30     15:00
11  ...  2025-01-11 20:58:07+05:30  2025-01-11 21:03:42+05:30     15:00
12  ...  2024-12-28 22:42:26+05:30  2024-12-28 22:58:49+05:30     15:00
13  ...  2024-12-11 20:31:14+05:30  2024-12-11 20:36:42+05:30     15:00

    better_than total_questions            rank_text mistakes_corrected  \
0           107             100   Topic Rank - #-171                  9
1           395              23  Topic Rank - #-9140                  3
2           115             100   Topic Rank - #-418                 11
3           152              23  Topic Rank - #-1598                  1
4            35             100   Topic Rank - #2023                  0
5            43              89   Topic Rank - #1810                  0
6           152              23  Topic Rank - #-1598                  0
7            18              59   Topic Rank - #2556                  0
8           375              20  Topic Rank - #-8479                  4
9           177              22  Topic Rank - #-2380                  0
10          270              41  Topic Rank - #-5215                 12
11          286              22  Topic Rank - #-5764                  0
12           92              55    Topic Rank - #301                  0
13           23             100   Topic Rank - #2392                  0

   initial_mistake_count                                       response_map  \
0                     12  {'2523': 10109, '2529': 10130, '2533': 10149, ...
1                      3  {'48': 192, '49': 197, '50': 199, '51': 203, '...
2                     12  {'2523': 10109, '2525': 10117, '2528': 10127, ...
3                      2  {'49': 197, '52': 208, '53': 212, '54': 217, '...
4                     20  {'2521': 10099, '2523': 10107, '2532': 10145, ...
5                     16  {'3043': 12184, '3044': 12186, '3046': 12194, ...
6                      9  {'48': 193, '49': 197, '50': 202, '51': 203, '...
7                      7  {'473': 1893, '474': 1898, '475': 1901, '487':...
8                      4  {'770': 3084, '771': 3085, '772': 3091, '773':...
9                      0  {'612': 2451, '613': 2454, '614': 2460, '619':...
10                    14  {'790': 3160, '793': 3172, '794': 3177, '796':...
11                     3  {'611': 2447, '612': 2451, '613': 2454, '614':...
12                    17  {'3132': 12542, '3135': 12554, '3137': 12561, ...
13                     3  {'2417': 9684, '2425': 9715, '2435': 9754, '24...

                                                 quiz
0   {'id': 51, 'name': None, 'title': 'Human Physi...
1   {'id': 6, 'name': None, 'title': 'Human Physio...
2   {'id': 51, 'name': None, 'title': 'Human Physi...
3   {'id': 6, 'name': None, 'title': 'Human Physio...
4   {'id': 51, 'name': None, 'title': 'Human Physi...
5   {'id': 57, 'name': None, 'title': 'Reproductio...
6   {'id': 6, 'name': None, 'title': 'Human Physio...
7   {'id': 20, 'name': None, 'title': 'PRINCIPLES ...
8   {'id': 24, 'name': None, 'title': 'MICROBES IN...
9   {'id': 18, 'name': None, 'title': 'REPRODUCTIV...
10  {'id': 25, 'name': None, 'title': 'HUMAN HEALT...
11  {'id': 18, 'name': None, 'title': 'REPRODUCTIV...
12  {'id': 58, 'name': None, 'title': 'Reproductio...
13  {'id': 50, 'name': None, 'title': 'Human Physi...

[14 rows x 26 columns]

In [28]:
result.head()

,id,quiz_id,user_id,submitted_at,created_at,updated_at,score,trophy_level,accuracy,speed,...,started_at,ended_at,duration,better_than,total_questions,rank_text,mistakes_corrected,initial_mistake_count,response_map,quiz
0,336497,51,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-17 15:30:18.027000+05:30,2025-01-17 15:30:18.044000+05:30,2025-01-17 15:30:18.044000+05:30,108,2,90 %,100,...,2025-01-17 15:18:30+05:30,2025-01-17 15:30:15+05:30,15:00,107,100,Topic Rank - #-171,9,12,"{'2523': 10109, '2529': 10130, '2533': 10149, ...","{'id': 51, 'name': None, 'title': 'Human Physi..."
1,336448,6,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-17 15:17:44.042000+05:30,2025-01-17 15:17:44.056000+05:30,2025-01-17 15:17:44.056000+05:30,92,1,100 %,100,...,2025-01-17 15:07:45+05:30,2025-01-17 15:17:41+05:30,15:00,395,23,Topic Rank - #-9140,3,3,"{'48': 192, '49': 197, '50': 199, '51': 203, '...","{'id': 6, 'name': None, 'title': 'Human Physio..."
2,333330,51,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-16 20:13:19.682000+05:30,2025-01-16 20:13:19.699000+05:30,2025-01-16 20:13:19.699000+05:30,116,2,96 %,100,...,2025-01-16 20:01:10+05:30,2025-01-16 20:13:18+05:30,15:00,115,100,Topic Rank - #-418,11,12,"{'2523': 10109, '2525': 10117, '2528': 10127, ...","{'id': 51, 'name': None, 'title': 'Human Physi..."
3,333242,6,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-16 20:00:11.562000+05:30,2025-01-16 20:00:11.573000+05:30,2025-01-16 20:00:11.573000+05:30,36,2,90 %,100,...,2025-01-16 19:52:57+05:30,2025-01-16 20:00:09+05:30,15:00,152,23,Topic Rank - #-1598,1,2,"{'49': 197, '52': 208, '53': 212, '54': 217, '...","{'id': 6, 'name': None, 'title': 'Human Physio..."
4,329504,51,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-15 20:34:39.462000+05:30,2025-01-15 20:34:39.478000+05:30,2025-01-15 20:34:39.478000+05:30,36,3,31 %,96,...,2025-01-15 20:21:25+05:30,2025-01-15 20:34:38+05:30,15:00,35,100,Topic Rank - #2023,0,20,"{'2521': 10099, '2523': 10107, '2532': 10145, ...","{'id': 51, 'name': None, 'title': 'Human Physi..."

In [26]:
hs.head()

,id,quiz_id,user_id,submitted_at,created_at,updated_at,score,trophy_level,accuracy,speed,...,started_at,ended_at,duration,better_than,total_questions,rank_text,mistakes_corrected,initial_mistake_count,response_map,quiz
0,336497,51,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-17 15:30:18.027000+05:30,2025-01-17 15:30:18.044000+05:30,2025-01-17 15:30:18.044000+05:30,108,2,90 %,100,...,2025-01-17 15:18:30+05:30,2025-01-17 15:30:15+05:30,15:00,107,100,Topic Rank - #-171,9,12,"{'2523': 10109, '2529': 10130, '2533': 10149, ...","{'id': 51, 'name': None, 'title': 'Human Physi..."
1,336448,6,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-17 15:17:44.042000+05:30,2025-01-17 15:17:44.056000+05:30,2025-01-17 15:17:44.056000+05:30,92,1,100 %,100,...,2025-01-17 15:07:45+05:30,2025-01-17 15:17:41+05:30,15:00,395,23,Topic Rank - #-9140,3,3,"{'48': 192, '49': 197, '50': 199, '51': 203, '...","{'id': 6, 'name': None, 'title': 'Human Physio..."
2,333330,51,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-16 20:13:19.682000+05:30,2025-01-16 20:13:19.699000+05:30,2025-01-16 20:13:19.699000+05:30,116,2,96 %,100,...,2025-01-16 20:01:10+05:30,2025-01-16 20:13:18+05:30,15:00,115,100,Topic Rank - #-418,11,12,"{'2523': 10109, '2525': 10117, '2528': 10127, ...","{'id': 51, 'name': None, 'title': 'Human Physi..."
3,333242,6,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-16 20:00:11.562000+05:30,2025-01-16 20:00:11.573000+05:30,2025-01-16 20:00:11.573000+05:30,36,2,90 %,100,...,2025-01-16 19:52:57+05:30,2025-01-16 20:00:09+05:30,15:00,152,23,Topic Rank - #-1598,1,2,"{'49': 197, '52': 208, '53': 212, '54': 217, '...","{'id': 6, 'name': None, 'title': 'Human Physio..."
4,329504,51,YcDFSO4ZukTJnnFMgRNVwZTE4j42,2025-01-15 20:34:39.462000+05:30,2025-01-15 20:34:39.478000+05:30,2025-01-15 20:34:39.478000+05:30,36,3,31 %,96,...,2025-01-15 20:21:25+05:30,2025-01-15 20:34:38+05:30,15:00,35,100,Topic Rank - #2023,0,20,"{'2521': 10099, '2523': 10107, '2532': 10145, ...","{'id': 51, 'name': None, 'title': 'Human Physi..."

In [29]:
result.shape

(14, 26)